nrinaudo/kantan.codecs

cats/src/test/scala/kantan/codecs/cats/ResultTests.scala, core/src/test/scala/kantan/codecs/CodecCompanionTests.scala, core/src/test/scala/kantan/codecs/DecoderCompanionTests.scala, core/src/test/scala/kantan/codecs/EncoderCompanionTests.scala, core/src/test/scala/kantan/codecs/ResultCompanionTests.scala, core/src/test/scala/kantan/codecs/ResultTests.scala, core/src/test/scala/kantan/codecs/exported/DerivedCodecTests.scala, core/src/test/scala/kantan/codecs/resource/ResourceIteratorTests.scala, core/src/test/scala/kantan/codecs/resource/bom/BomReaderTests.scala, core/src/test/scala/kantan/codecs/resource/bom/BomWriterTests.scala, core/src/test/scala/kantan/codecs/strings/ErrorsTests.scala, laws/src/test/scala/kantan/codecs/laws/CodecValueTests.scala, scalaz/src/test/scala/kantan/codecs/scalaz/ResultTests.scala
=> Use scalatest DSL instead of assertions.

build.sbt, core/src/test/scala/kantan/codecs/ResultTests.scala, core/src/test/scala/kantan/codecs/resource/ResourceIteratorTests.scala, scalatest/src/main/scala/kantan/codecs/scalatest/Resources.scala, scalatest/src/main/scala/kantan/codecs/scalatest/ResultValues.scala, scalatest/src/test/scala/kantan/codecs/scalatest/ResultValuesTests.scala
=> Implement scalatest syntax for `Result`.

docs/src/site-preprocess/index.md
=> #43: Fix link to latest version in companion site

codecov.yml
=> [49] Disable codecov comments

build.sbt, core/src/main/scala/kantan/codecs/error/Error.scala, core/src/main/scala/kantan/codecs/error/IsError.scala, project/Versions.scala, refined-laws/src/main/scala/kantan/codecs/refined/arbitrary.scala, refined/src/main/scala/kantan/codecs/refined/RefinedInstances.scala, refined/src/main/scala/kantan/codecs/refined/package.scala, refined/src/test/scala/kantan/codecs/refined/RefinedCodecTests.scala
=> Add support for refined

cats/src/main/scala/kantan/codecs/cats/LowPriorityCatsInstances.scala, core/src/test/scala/kantan/codecs/ResultTests.scala, laws/src/main/scala/kantan/codecs/laws/discipline/arbitrary.scala, project/plugins.sbt, scalatest/src/main/scala/kantan/codecs/scalatest/ResultValues.scala, scalaz/src/main/scala/kantan/codecs/scalaz/LowPriorityScalazInstances.scala
=> 57: Fix issues raised by stricter scalac options

.travis.yml
=> [#61] Clean-up travis JDKs

refined/core/src/main/scala/kantan/codecs/refined/RefinedInstances.scala, refined/core/src/main/scala/kantan/codecs/refined/package.scala
=> [#73] Split refined instances into Decoder & Encoder

build.sbt, enumeratum/core/src/main/scala/kantan/codecs/enumeratum/EnumInstances.scala, enumeratum/core/src/main/scala/kantan/codecs/enumeratum/package.scala, enumeratum/core/src/main/scala/kantan/codecs/enumeratum/values/ValueEnumInstances.scala, enumeratum/core/src/main/scala/kantan/codecs/enumeratum/values/package.scala, enumeratum/core/src/test/scala/kantan/codecs/enumeratum/EnumCodecTests.scala, enumeratum/core/src/test/scala/kantan/codecs/enumeratum/values/ByteEnumCodecTests.scala, enumeratum/core/src/test/scala/kantan/codecs/enumeratum/values/CharEnumCodecTests.scala, enumeratum/core/src/test/scala/kantan/codecs/enumeratum/values/IntEnumCodecTests.scala, enumeratum/core/src/test/scala/kantan/codecs/enumeratum/values/LongEnumCodecTests.scala, enumeratum/core/src/test/scala/kantan/codecs/enumeratum/values/ShortEnumCodecTests.scala, enumeratum/core/src/test/scala/kantan/codecs/enumeratum/values/StringEnumCodecTests.scala, enumeratum/laws/src/main/scala/kantan/codecs/enumeratum/laws/discipline/Enumerated.scala, enumeratum/laws/src/main/scala/kantan/codecs/enumeratum/laws/discipline/arbitrary.scala, project/Versions.scala
=> [#63] Add support for enumeratum

shapeless/core/src/main/scala/kantan/codecs/shapeless/ShapelessInstances.scala, shapeless/core/src/test/scala/kantan/codecs/shapeless/InstancesTests.scala
=> [#84] Derive Decoder[CNil] instances automatically

core/src/main/scala/kantan/codecs/strings/StringCodec.scala, core/src/main/scala/kantan/codecs/strings/StringDecoder.scala, core/src/main/scala/kantan/codecs/strings/codecs.scala, scalatest/src/main/scala/kantan/codecs/scalatest/ResultValues.scala
=> [#86] Flag all doctests samples with @example.

cats/core/src/main/scala/kantan/codecs/cats/CatsInstances.scala, cats/core/src/main/scala/kantan/codecs/cats/package.scala, cats/core/src/test/scala/kantan/codecs/cats/DecodeErrorTests.scala, cats/core/src/test/scala/kantan/codecs/cats/DecoderTests.scala, cats/laws/src/main/scala/kantan/codecs/cats/laws/discipline/equality.scala, core/src/main/scala/kantan/codecs/Decoder.scala, laws/src/main/scala/kantan/codecs/laws/discipline/CodecTests.scala, laws/src/main/scala/kantan/codecs/laws/discipline/DecoderTests.scala, project/Versions.scala
=> [#80] Improve cats instances

laws/src/main/scala/kantan/codecs/laws/discipline/arbitrary.scala
=> [#93] Provide default Arbitrary instances for Decoder and Encoder

build.sbt, libra/core/src/main/scala/kantan/codecs/libra/LibraInstances.scala, libra/core/src/main/scala/kantan/codecs/libra/package.scala, libra/core/src/test/scala/kantan/codecs/libra/LibraCodecTests.scala, libra/laws/src/main/scala/kantan/codecs/libra/laws/discipline/arbitrary.scala, libra/laws/src/main/scala/kantan/codecs/libra/laws/discipline/package.scala, project/Versions.scala
=> [#75] Implement a libra module

scalaz/core/src/main/scala/kantan/codecs/scalaz/ScalazInstances.scala, scalaz/core/src/main/scala/kantan/codecs/scalaz/package.scala, scalaz/core/src/test/scala/kantan/codecs/scalaz/DecodeErrorTests.scala, scalaz/core/src/test/scala/kantan/codecs/scalaz/DecoderTests.scala, scalaz/laws/src/main/scala/kantan/codecs/scalaz/laws/discipline/ScalazDisciplineSuite.scala
=> [#81] Improve scalaz instances

core/shared/src/main/scala/kantan/codecs/strings/StringCodec.scala, core/shared/src/main/scala/kantan/codecs/strings/StringEncoder.scala
=> [#98] Update string codecs to use the relevant companion object helpers

scalaz/core/shared/src/test/scala/kantan/codecs/scalaz/DisjunctionCodecTests.scala, scalaz/core/shared/src/test/scala/kantan/codecs/scalaz/MaybeCodecTests.scala, scalaz/laws/shared/src/main/scala/kantan/codecs/scalaz/laws/discipline/arbitrary.scala
This saves us an annoying import everywhere else.
Fixes #29.
=> [#29] "Proxy" interesting scalaz arbitrary instances

core/shared/src/main/scala/kantan/codecs/Result.scala
=> [#89] Implement WithError (WithDefault using IsError)

java8/core/src/main/scala/kantan/codecs/strings/java8/Format.scala, java8/core/src/main/scala/kantan/codecs/strings/java8/TimeCodecCompanion.scala, java8/core/src/main/scala/kantan/codecs/strings/java8/TimeDecoderCompanion.scala, java8/core/src/main/scala/kantan/codecs/strings/java8/TimeEncoderCompanion.scala, java8/core/src/main/scala/kantan/codecs/strings/java8/package.scala, java8/core/src/test/scala/kantan/codecs/strings/java8/FormatTests.scala, java8/core/src/test/scala/kantan/codecs/strings/java8/TimeCodecCompanionTests.scala, java8/core/src/test/scala/kantan/codecs/strings/java8/TimeDecoderCompanionTests.scala, java8/core/src/test/scala/kantan/codecs/strings/java8/TimeEncoderCompanionTests.scala, java8/core/src/test/scala/kantan/codecs/strings/java8/codec.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/Format.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/JodaTimeCodecCompanion.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/JodaTimeDecoderCompanion.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/JodaTimeEncoderCompanion.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/package.scala, joda-time/core/src/test/scala/kantan/codecs/strings/joda/time/DateTimeCodecTests.scala, joda-time/core/src/test/scala/kantan/codecs/strings/joda/time/FormatTests.scala, joda-time/core/src/test/scala/kantan/codecs/strings/joda/time/JodaTimeCodecCompanionTests.scala, joda-time/core/src/test/scala/kantan/codecs/strings/joda/time/JodaTimeDecoderCompanionTests.scala, joda-time/core/src/test/scala/kantan/codecs/strings/joda/time/JodaTimeEncoderCompanionTests.scala, joda-time/core/src/test/scala/kantan/codecs/strings/joda/time/LocalDateCodecTests.scala, joda-time/core/src/test/scala/kantan/codecs/strings/joda/time/LocalDateTimeCodecTests.scala, joda-time/core/src/test/scala/kantan/codecs/strings/joda/time/LocalTimeCodecTests.scala, joda-time/core/src/test/scala/kantan/codecs/strings/joda/time/codec.scala, joda-time/laws/src/main/scala/kantan/codecs/strings/joda/time/laws/discipline/arbitrary.scala, joda-time/laws/src/main/scala/kantan/codecs/strings/joda/time/laws/discipline/package.scala
=> [#108] Simplify the various time companion helpers

build.sbt, java8/core/src/main/scala/kantan/codecs/strings/java8/Format.scala, java8/core/src/main/scala/kantan/codecs/strings/java8/FormatVerifier.scala, java8/core/src/main/scala/kantan/codecs/strings/java8/TimeCodecCompanion.scala, java8/core/src/main/scala/kantan/codecs/strings/java8/TimeDecoderCompanion.scala, java8/core/src/main/scala/kantan/codecs/strings/java8/TimeEncoderCompanion.scala, java8/core/src/main/scala/kantan/codecs/strings/java8/ToFormatLiteral.scala, java8/core/src/main/scala/kantan/codecs/strings/java8/package.scala, java8/core/src/test/scala/kantan/codecs/strings/java8/FormatTests.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/Format.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/FormatVerifier.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/JodaTimeCodecCompanion.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/JodaTimeDecoderCompanion.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/JodaTimeEncoderCompanion.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/ToFormatLiteral.scala, joda-time/core/src/main/scala/kantan/codecs/strings/joda/time/package.scala, joda-time/core/src/test/scala/kantan/codecs/strings/joda/time/FormatTests.scala, project/Versions.scala
=> [#113] Add date/time format literals support

core/jvm/src/test/scala/kantan/codecs/collection/SerialisationTests.scala, core/shared/src/test/scala/kantan/codecs/collection/HasBuilderTests.scala
Improves overall code coverage.
=> [coverage] Add tests for non-covered bits

.travis.yml, project/Versions.scala, project/build.properties, project/plugins.sbt
=> [#120] Update to Scala 2.12.6

core/jvm/src/main/scala/kantan/codecs/resource/PlatformSpecificInstances.scala, core/shared/src/main/scala/kantan/codecs/resource/CloseResult.scala, core/shared/src/main/scala/kantan/codecs/resource/OpenResult.scala, core/shared/src/main/scala/kantan/codecs/resource/ProcessResult.scala, core/shared/src/main/scala/kantan/codecs/resource/ResourceError.scala, core/shared/src/main/scala/kantan/codecs/resource/ResourceResult.scala
=> [#122] Improve ResourceError

core/shared/src/main/scala/kantan/codecs/ResultCompanion.scala, core/shared/src/main/scala/kantan/codecs/resource/package.scala
=> [#125] Fixes various scaladoc warnings
